# Generated by Django 4.1.7 on 2023-02-17 13:58

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nbe_participant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=6)]),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('Person', 'event')},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.date(2023, 2, 17))), name='the event date is invalid'),
        ),
    ]
